name:                videomaker
version:             0.1.0.0
github:              "Confectio/videomaker"
license:             BSD3
author:              "Leonard Fichtner"
maintainer:          "leonard.fichtner@web.de"
copyright:           "2021 Leonard Fichtner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Confectio/videomaker#readme>

dependencies:
- base >= 4.7 && < 5
- stb-image-redux
- vector
- optparse-applicative
- process

library:
  source-dirs: src

executables:
  videomaker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - videomaker

tests:
  videomaker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - videomaker
